In [1]:
from ler.rates import LeR

ler = LeR(npool=8, verbose=True)

Setting multiprocessing start method to 'fork'
z_to_luminosity_distance interpolator will be loaded from ./interpolator_pickle/z_to_luminosity_distance/z_to_luminosity_distance_0.pickle
differential_comoving_volume interpolator will be loaded from ./interpolator_pickle/differential_comoving_volume/differential_comoving_volume_0.pickle
merger_rate_density interpolator will be loaded from ./interpolator_pickle/merger_rate_density/merger_rate_density_0.pickle
z_to_Dc interpolator will be loaded from ./interpolator_pickle/z_to_Dc/z_to_Dc_0.pickle
Dc_to_z interpolator will be loaded from ./interpolator_pickle/Dc_to_z/Dc_to_z_0.pickle
angular_diameter_distance interpolator will be loaded from ./interpolator_pickle/angular_diameter_distance/angular_diameter_distance_0.pickle
differential_comoving_volume interpolator will be loaded from ./interpolator_pickle/differential_comoving_volume/differential_comoving_volume_1.pickle
velocity_dispersion_ewoud interpolator will be loaded from ./interpola

interpolation for each mass_ratios: 100%|███████████████████████████| 50/50 [01:28<00:00,  1.77s/it]


 # LeR set up params:
npool = 4,
z_min = 0.0,
z_max = 10.0,
event_type = 'BBH',
size = 100000,
batch_size = 50000,
cosmology = LambdaCDM(H0=70.0 km / (Mpc s), Om0=0.3, Ode0=0.7, Tcmb0=0.0 K, Neff=3.04, m_nu=None, Ob0=None),
snr_finder = <bound method GWSNR.snr of <gwsnr.gwsnr.GWSNR object at 0x117f3d540>>,
json_file_names = {'ler_params': 'ler_params.json', 'unlensed_param': 'unlensed_param.json', 'unlensed_param_detectable': 'unlensed_param_detectable.json', 'lensed_param': 'lensed_param.json', 'lensed_param_detectable': 'lensed_param_detectable.json'},
interpolator_directory = './interpolator_pickle',
ler_directory = './ler_data',

 # LeR also takes CBCSourceParameterDistribution class params as kwargs, as follows:
source_priors = {'merger_rate_density': 'merger_rate_density_bbh_popI_II_oguri2018', 'source_frame_masses': 'binary_masses_BBH_popI_II_powerlaw_gaussian', 'zs': 'sample_source_redshift', 'geocent_time': 'sampler_uniform', 'ra': 'sampler_uniform', 'dec': 'sampler_cosine', 

In [5]:
ler.selecting_n_lensed_detectable_events?

Signature:
ler.selecting_n_lensed_detectable_events(
    size=100,
    batch_size=None,
    snr_threshold=[8.0, 8.0],
    pdet_threshold=0.5,
    num_img=[1, 1],
    combine_image_snr=False,
    snr_cut_for_combine_image_snr=4.0,
    resume=False,
    detectability_condition='step_function',
    output_jsonfile='n_lensed_params_detectable.json',
    meta_data_file='meta_lensed.json',
    trim_to_size=True,
    nan_to_num=False,
    snr_recalculation=False,
    snr_threshold_recalculation=[[4, 4], [12, 12]],
)
Docstring:
Function to generate n lensed detectable events. This fuction only samples the lensed parameters and save only the detectable events in json file. It also records metadata in the JSON file, which includes the total number of events and the cumulative rate of events. This functionality is particularly useful for generating a fixed or large number of detectable events until the event rates stabilize.

Parameters
----------
size : `int`
    number of samples.
    default s

In [26]:
ler.selecting_n_lensed_detectable_events(
    size=10000, 
    snr_threshold=8.0,
    num_img=4,
    batch_size=100000, 
    resume=True);

collected number of detectable events =  36


100%|█████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 31.21it/s]


given detectability_condition == step_function
collected number of detectable events =  65
total number of events =  200000
total rate (yr^-1): 0.07378784388014775


100%|█████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 21.58it/s]


given detectability_condition == step_function
collected number of detectable events =  94
total number of events =  300000
total rate (yr^-1): 0.07113904948445014


  1%|▋                                                      | 1278/100000 [00:00<00:34, 2891.44it/s]


KeyboardInterrupt: 

In [20]:
from ler.utils import get_param_from_json

In [21]:
param = get_param_from_json('./ler_data/n_lensed_params_detectable.json')

In [22]:
param.keys()

dict_keys(['zl', 'zs', 'sigma', 'q', 'theta_E', 'phi', 'e1', 'e2', 'gamma1', 'gamma2', 'gamma', 'geocent_time', 'ra', 'dec', 'phase', 'psi', 'theta_jn', 'luminosity_distance', 'mass_1_source', 'mass_2_source', 'mass_1', 'mass_2', 'x0_image_positions', 'x1_image_positions', 'magnifications', 'time_delays', 'image_type', 'n_images', 'x_source', 'y_source', 'effective_luminosity_distance', 'effective_geocent_time', 'snr_net', 'L1', 'H1', 'V1'])

In [23]:
param['magnifications']

array([[ 2.65251115e+01,  5.17499080e+01, -5.46611825e+01,
        -1.87644563e+01],
       [ 5.49080328e+00,  1.83807203e+01, -1.28928478e+01,
        -8.09957047e+00],
       [ 9.24535161e+00,  1.71108052e+01, -1.39129148e+01,
        -9.30452791e+00],
       [ 1.46826569e+01,  1.95522118e+01, -1.61781550e+01,
        -1.29928437e+01],
       [ 1.04838805e+01,  2.13699263e+01, -2.23469694e+01,
        -5.25485273e+00],
       [ 2.82479917e+00,  2.84112724e+00, -1.46295574e+00,
        -1.45934105e+00],
       [ 1.02979850e+01,  3.02374768e+01, -1.85516284e+01,
        -1.66785947e+01],
       [ 2.49758980e+01,  2.72462648e+01, -3.66259873e+01,
        -1.13125334e+01],
       [ 9.67069511e+00,  1.49686575e+01, -1.68413814e+01,
        -4.56606412e+00],
       [ 2.39973183e+01,  2.71690536e+01, -3.74275495e+01,
        -1.27343326e+01],
       [ 5.49990402e+00,  1.60923456e+03, -1.59642533e+03,
        -1.52329583e+01],
       [ 6.29023269e+00,  8.20370102e+00, -6.95612622e+00,
      

In [24]:
param['snr_net']

array([[  9.56771698,  21.60441593,  23.19543723,  13.06459951],
       [ 14.73576083,  24.67406952,  13.04494986,  15.89476167],
       [ 18.08430129,  12.81785682,  22.01475093,  17.87928517],
       [  9.80733292,  15.84847178,  13.67626797,   8.27225837],
       [ 12.10244256,  18.24761792,  13.25859778,   8.23757337],
       [ 12.53147083,  11.93253263,   9.92592971,   9.79990427],
       [  8.54662852,  15.55624424,  15.99665498,  10.06969669],
       [ 13.72102469,   9.51112829,  12.85392883,   8.79470911],
       [ 10.05330197,  11.04593558,  15.82104965,   8.81871187],
       [ 25.8251692 ,  22.07528622,  32.37696644,  24.88051952],
       [ 12.72877576, 189.00260562, 188.24891601,  23.79909534],
       [ 16.6363947 ,  15.6137529 ,  18.86868332,  19.61273857],
       [ 12.60030528,   9.93948258,  11.5151395 ,   9.449354  ],
       [  8.27714039,   9.50297382,  13.04002971,  11.88111491],
       [  9.54001357,  18.2203677 ,  12.2250158 ,   8.32422552],
       [ 11.05117753,  12

In [25]:
param['effective_geocent_time']

array([[1.24157225e+09, 1.24160940e+09, 1.24161513e+09, 1.24169595e+09],
       [1.25096450e+09, 1.25425325e+09, 1.25436808e+09, 1.25466384e+09],
       [1.25929468e+09, 1.26159064e+09, 1.26206722e+09, 1.26292941e+09],
       [1.24643915e+09, 1.24673118e+09, 1.24698691e+09, 1.24714317e+09],
       [1.25108913e+09, 1.25133435e+09, 1.25135934e+09, 1.25210243e+09],
       [1.24168822e+09, 1.24169111e+09, 1.24185591e+09, 1.24185649e+09],
       [1.25916455e+09, 1.26119939e+09, 1.26134856e+09, 1.26140158e+09],
       [1.25632270e+09, 1.25637937e+09, 1.25655755e+09, 1.25803467e+09],
       [1.24115364e+09, 1.24181267e+09, 1.24202678e+09, 1.24545213e+09],
       [1.25718297e+09, 1.25724824e+09, 1.25744161e+09, 1.25866518e+09],
       [1.25376009e+09, 1.25426386e+09, 1.25426386e+09, 1.25428213e+09],
       [1.24116581e+09, 1.24118537e+09, 1.24120168e+09, 1.24122101e+09],
       [1.25353745e+09, 1.25390930e+09, 1.25394705e+09, 1.25424244e+09],
       [1.24339020e+09, 1.24764577e+09, 1.24774927e

In [31]:
import json
import numpy as np
param = json.load(open('./ler_data/n_lensed_params_detectable.json'))

In [32]:
np.array(param['magnifications'])

array([[ 2.65251115e+01,  5.17499080e+01, -5.46611825e+01,
        -1.87644563e+01],
       [ 5.49080328e+00,  1.83807203e+01, -1.28928478e+01,
        -8.09957047e+00],
       [ 9.24535161e+00,  1.71108052e+01, -1.39129148e+01,
        -9.30452791e+00],
       [ 1.46826569e+01,  1.95522118e+01, -1.61781550e+01,
        -1.29928437e+01],
       [ 1.04838805e+01,  2.13699263e+01, -2.23469694e+01,
        -5.25485273e+00],
       [ 2.82479917e+00,  2.84112724e+00, -1.46295574e+00,
        -1.45934105e+00],
       [ 1.02979850e+01,  3.02374768e+01, -1.85516284e+01,
        -1.66785947e+01],
       [ 2.49758980e+01,  2.72462648e+01, -3.66259873e+01,
        -1.13125334e+01],
       [ 9.67069511e+00,  1.49686575e+01, -1.68413814e+01,
        -4.56606412e+00],
       [ 2.39973183e+01,  2.71690536e+01, -3.74275495e+01,
        -1.27343326e+01],
       [ 5.49990402e+00,  1.60923456e+03, -1.59642533e+03,
        -1.52329583e+01],
       [ 6.29023269e+00,  8.20370102e+00, -6.95612622e+00,
      